### PR TITLE
dcos_metrics: Don't 500 after receiving NaN values

### PR DESCRIPTION
**Pull request by branden**
If the dcos-metrics HTTP producer stores a NaN value in a container's app metrics and those metrics are requested, it'll fail to serialize the NaN to JSON and return a 500 response. This PR causes `producerTranslator.Translate()` to convert NaN values to an empty string, preventing serialization errors.

https://jira.mesosphere.com/browse/DCOS_OSS-4088

DC/OS PR: https://github.com/dcos/dcos/pull/3436

### CODE REVIEW

**Comment by branden** [comment]
CI is failing due to https://jira.mesosphere.com/browse/DCOS_OSS-4096. See #11.

**Review by janisz — DISMISSED** [review]

**Comment by janisz** [comment]
Code looks good but there is a data race.

**Review by philipnrmn — DISMISSED** [review]
LGTM

**Review by philipnrmn — APPROVED** [review]
re-approving after rebase

**Pull request merged**
